name: dart_test_adapter
version: 0.1.0
description: Provides a Dart API for interacting with `dart test`/`flutter test` programatically
homepage: "https://github.com/invertase/spec"

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  test: ^1.17.8

dev_dependencies:
  build_runner: ^2.1.7
  freezed: ^1.1.1
  json_serializable: ^6.1.3
